// frontend/src/pages/billing/Invoices.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Table, Card, Typography, Select, Space, Button, message, DatePicker, Popconfirm, Modal } from 'antd';
import { PlusOutlined, ReloadOutlined, DownloadOutlined, PrinterOutlined, UserOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import StatusTag from '../../components/StatusTag';
import { getInvoices, generateInvoices, updateInvoice, downloadInvoicePdf } from '../../api/billing';
import { getCustomers } from '../../api/customers';
import type { Invoice } from '../../api/billing';

const Invoices = () => {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState<string | undefined>();
  const [dateRange, setDateRange] = useState<[dayjs.Dayjs | null, dayjs.Dayjs | null] | null>(null);

  const [genForCustomerOpen, setGenForCustomerOpen] = useState(false);
  const [selectedCustomerId, setSelectedCustomerId] = useState<string | undefined>();
  const [customerSearch, setCustomerSearch] = useState('');

  const { data, isLoading } = useQuery({
    queryKey: ['invoices', page, statusFilter, dateRange],
    queryFn: () =>
      getInvoices({
        page,
        size: 20,
        status: statusFilter,
        from_date: dateRange?.[0]?.format('YYYY-MM-DD'),
        to_date: dateRange?.[1]?.format('YYYY-MM-DD'),
      }).then((r) => r.data),
  });

  const { data: customersData } = useQuery({
    queryKey: ['customers-search', customerSearch],
    queryFn: () => getCustomers({ page: 1, page_size: 50, search: customerSearch || undefined }),
    enabled: genForCustomerOpen,
  });

  const generateMut = useMutation({
    mutationFn: (customerId?: string) => generateInvoices(customerId),
    onSuccess: (res) => {
      message.success(`Generated ${res.data.generated} invoice(s), skipped ${res.data.skipped}`);
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    },
    onError: () => message.error('Failed to generate invoices'),
  });

  const voidMut = useMutation({
    mutationFn: (id: string) => updateInvoice(id, { status: 'void' }),
    onSuccess: () => {
      message.success('Invoice voided');
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    },
    onError: () => message.error('Failed to void invoice'),
  });

  const handleGenerateForCustomer = () => {
    if (!selectedCustomerId) return;
    generateMut.mutate(selectedCustomerId, {
      onSuccess: () => {
        setGenForCustomerOpen(false);
        setSelectedCustomerId(undefined);
        setCustomerSearch('');
      },
    });
  };

  const columns = [
    {
      title: 'Customer',
      dataIndex: 'customer_name',
      key: 'customer',
      ellipsis: true,
    },
    {
      title: 'Amount',
      key: 'amount',
      render: (_: unknown, r: Invoice) => `₱${Number(r.amount).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`,
      width: 120,
    },
    {
      title: 'Paid',
      key: 'total_paid',
      render: (_: unknown, r: Invoice) => r.total_paid ? `₱${Number(r.total_paid).toLocaleString('en-PH', { minimumFractionDigits: 2 })}` : '₱0.00',
      width: 120,
    },
    {
      title: 'Due Date',
      dataIndex: 'due_date',
      key: 'due',
      width: 110,
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (s: string) => <StatusTag status={s} />,
      width: 100,
    },
    {
      title: 'Issued',
      dataIndex: 'issued_at',
      key: 'issued',
      render: (d: string) => dayjs(d).format('YYYY-MM-DD'),
      width: 110,
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 160,
      render: (_: unknown, r: Invoice) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<DownloadOutlined />}
            onClick={async () => {
              try {
                const res = await downloadInvoicePdf(r.id);
                const url = window.URL.createObjectURL(new Blob([res.data]));
                const link = document.createElement('a');
                link.href = url;
                link.download = `invoice-${r.id.slice(0, 8)}.pdf`;
                link.click();
                window.URL.revokeObjectURL(url);
              } catch { message.error('Failed to download PDF'); }
            }}
          >
            PDF
          </Button>
          <Button
            type="link"
            size="small"
            icon={<PrinterOutlined />}
            onClick={() => window.open(`/api/v1/billing/invoices/${r.id}/pdf`, '_blank')}
          />
          {r.status !== 'void' && r.status !== 'paid' ? (
            <Popconfirm title="Void this invoice?" onConfirm={() => voidMut.mutate(r.id)}>
              <Button type="link" size="small" danger>Void</Button>
            </Popconfirm>
          ) : null}
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
        <Typography.Title level={4} style={{ margin: 0 }}>Invoices</Typography.Title>
        <Space>
          <Button
            icon={<UserOutlined />}
            onClick={() => setGenForCustomerOpen(true)}
          >
            Generate for Customer
          </Button>
          <Popconfirm
            title="Generate invoices for all active customers?"
            onConfirm={() => generateMut.mutate(undefined)}
          >
            <Button
              type="primary"
              icon={<PlusOutlined />}
              loading={generateMut.isPending}
            >
              Generate Invoices
            </Button>
          </Popconfirm>
        </Space>
      </div>
      <Card>
        <Space style={{ marginBottom: 16 }} wrap>
          <Select
            placeholder="Filter by status"
            allowClear
            style={{ width: 150 }}
            value={statusFilter}
            onChange={setStatusFilter}
          >
            <Select.Option value="pending">Pending</Select.Option>
            <Select.Option value="paid">Paid</Select.Option>
            <Select.Option value="overdue">Overdue</Select.Option>
            <Select.Option value="void">Void</Select.Option>
          </Select>
          <DatePicker.RangePicker
            onChange={(dates) => setDateRange(dates as [dayjs.Dayjs | null, dayjs.Dayjs | null] | null)}
          />
          <Button
            icon={<ReloadOutlined />}
            onClick={() => queryClient.invalidateQueries({ queryKey: ['invoices'] })}
          />
        </Space>
        <Table
          columns={columns}
          dataSource={data?.items || []}
          rowKey="id"
          loading={isLoading}
          pagination={{
            current: page,
            pageSize: 20,
            total: data?.total || 0,
            onChange: setPage,
            showTotal: (total) => `${total} invoices`,
          }}
        />
      </Card>

      {/* Generate for specific customer modal */}
      <Modal
        title="Generate Invoice for Customer"
        open={genForCustomerOpen}
        onCancel={() => { setGenForCustomerOpen(false); setSelectedCustomerId(undefined); setCustomerSearch(''); }}
        onOk={handleGenerateForCustomer}
        confirmLoading={generateMut.isPending}
        okButtonProps={{ disabled: !selectedCustomerId }}
        okText="Generate"
      >
        <Select
          showSearch
          style={{ width: '100%' }}
          placeholder="Search and select customer"
          filterOption={false}
          onSearch={setCustomerSearch}
          value={selectedCustomerId}
          onChange={setSelectedCustomerId}
          notFoundContent={customersData ? 'No customers found' : 'Type to search'}
        >
          {customersData?.data?.items?.map((c: any) => (
            <Select.Option key={c.id} value={c.id}>{c.full_name} ({c.pppoe_username})</Select.Option>
          ))}
        </Select>
      </Modal>
    </div>
  );
};

export default Invoices;

// frontend/src/pages/billing/Invoices.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import dayjs from 'dayjs'
import { getInvoices, generateInvoices, updateInvoice, downloadInvoicePdf, type Invoice } from '../../api/billing'
import { getCustomers, type Customer } from '../../api/customers'
import StatusBadge from '../../components/common/StatusBadge.vue'
import Modal from '../../components/common/Modal.vue'
import ConfirmDialog from '../../components/common/ConfirmDialog.vue'
import Pagination from '../../components/common/Pagination.vue'

const invoices = ref<Invoice[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = 20
const loading = ref(false)

// Filters
const filterStatus = ref('')
const filterFromDate = ref('')
const filterToDate = ref('')

// Generate All confirm
const showGenerateAllConfirm = ref(false)
const generateAllLoading = ref(false)

// Generate for Customer modal
const showGenerateModal = ref(false)
const generateCustomerLoading = ref(false)
const customerSearch = ref('')
const customerResults = ref<Customer[]>([])
const selectedCustomer = ref<Customer | null>(null)
const customerSearchLoading = ref(false)
const showCustomerDropdown = ref(false)

// Void confirm
const showVoidConfirm = ref(false)
const voidTarget = ref<Invoice | null>(null)
const voidLoading = ref(false)

async function fetchInvoices() {
  loading.value = true
  try {
    const params: Record<string, any> = { page: page.value, size: pageSize }
    if (filterStatus.value) params.status = filterStatus.value
    if (filterFromDate.value) params.from_date = filterFromDate.value
    if (filterToDate.value) params.to_date = filterToDate.value
    const { data } = await getInvoices(params)
    invoices.value = data.items
    total.value = data.total
  } catch (e) {
    console.error('Failed to fetch invoices', e)
  } finally {
    loading.value = false
  }
}

watch(page, fetchInvoices)

function applyFilters() {
  page.value = 1
  fetchInvoices()
}

// Customer search with debounce
let searchTimeout: ReturnType<typeof setTimeout> | null = null
function onCustomerSearch() {
  showCustomerDropdown.value = true
  selectedCustomer.value = null
  if (searchTimeout) clearTimeout(searchTimeout)
  searchTimeout = setTimeout(async () => {
    if (!customerSearch.value.trim()) {
      customerResults.value = []
      return
    }
    customerSearchLoading.value = true
    try {
      const { data } = await getCustomers({ search: customerSearch.value, page_size: 10 })
      customerResults.value = data.items
    } catch (e) {
      console.error('Customer search failed', e)
    } finally {
      customerSearchLoading.value = false
    }
  }, 300)
}

function selectCustomer(c: Customer) {
  selectedCustomer.value = c
  customerSearch.value = c.full_name
  showCustomerDropdown.value = false
}

async function handleGenerateForCustomer() {
  if (!selectedCustomer.value) return
  generateCustomerLoading.value = true
  try {
    await generateInvoices(selectedCustomer.value.id)
    showGenerateModal.value = false
    customerSearch.value = ''
    selectedCustomer.value = null
    fetchInvoices()
  } catch (e) {
    console.error('Generate failed', e)
  } finally {
    generateCustomerLoading.value = false
  }
}

async function handleGenerateAll() {
  generateAllLoading.value = true
  try {
    await generateInvoices()
    showGenerateAllConfirm.value = false
    fetchInvoices()
  } catch (e) {
    console.error('Generate all failed', e)
  } finally {
    generateAllLoading.value = false
  }
}

function openVoidConfirm(inv: Invoice) {
  voidTarget.value = inv
  showVoidConfirm.value = true
}

async function handleVoid() {
  if (!voidTarget.value) return
  voidLoading.value = true
  try {
    await updateInvoice(voidTarget.value.id, { status: 'void' })
    showVoidConfirm.value = false
    voidTarget.value = null
    fetchInvoices()
  } catch (e) {
    console.error('Void failed', e)
  } finally {
    voidLoading.value = false
  }
}

async function handleDownloadPdf(inv: Invoice) {
  try {
    const { data } = await downloadInvoicePdf(inv.id)
    const url = window.URL.createObjectURL(new Blob([data], { type: 'application/pdf' }))
    const a = document.createElement('a')
    a.href = url
    a.download = `invoice-${inv.id}.pdf`
    document.body.appendChild(a)
    a.click()
    a.remove()
    window.URL.revokeObjectURL(url)
  } catch (e) {
    console.error('PDF download failed', e)
  }
}

function handlePrint(inv: Invoice) {
  window.open(`/api/v1/billing/invoices/${inv.id}/pdf`, '_blank')
}

function formatCurrency(val: number | string) {
  return '₱' + Number(val).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

onMounted(fetchInvoices)
</script>

<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
      <h1 class="text-2xl font-bold text-gray-900">Invoices</h1>
      <div class="flex items-center gap-3">
        <button
          @click="showGenerateModal = true"
          class="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-hover transition-colors"
        >
          Generate for Customer
        </button>
        <button
          @click="showGenerateAllConfirm = true"
          class="px-4 py-2 text-sm font-medium text-primary bg-orange-50 border border-orange-200 rounded-lg hover:bg-orange-100 transition-colors"
        >
          Generate All
        </button>
      </div>
    </div>

    <!-- Filters -->
    <div class="rounded-xl bg-white shadow-sm border border-gray-100 p-4">
      <div class="flex flex-wrap items-end gap-4">
        <div>
          <label class="block text-xs font-medium text-gray-500 mb-1">Status</label>
          <select
            v-model="filterStatus"
            class="rounded-lg border border-gray-300 text-sm px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-colors"
          >
            <option value="">All</option>
            <option value="pending">Pending</option>
            <option value="paid">Paid</option>
            <option value="overdue">Overdue</option>
            <option value="void">Void</option>
          </select>
        </div>
        <div>
          <label class="block text-xs font-medium text-gray-500 mb-1">From</label>
          <input
            v-model="filterFromDate"
            type="date"
            class="rounded-lg border border-gray-300 text-sm px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-colors"
          />
        </div>
        <div>
          <label class="block text-xs font-medium text-gray-500 mb-1">To</label>
          <input
            v-model="filterToDate"
            type="date"
            class="rounded-lg border border-gray-300 text-sm px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-colors"
          />
        </div>
        <button
          @click="applyFilters"
          class="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-hover transition-colors"
        >
          <svg class="w-4 h-4 inline-block mr-1 -mt-0.5" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clip-rule="evenodd" /></svg>
          Refresh
        </button>
      </div>
    </div>

    <!-- Table -->
    <div class="rounded-xl bg-white shadow-sm border border-gray-100 overflow-hidden">
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="bg-gray-50 border-b border-gray-100">
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-left">Customer</th>
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-right">Amount</th>
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-right">Paid</th>
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-left">Due Date</th>
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-left">Status</th>
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-left">Issued</th>
              <th class="px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider text-right">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-50">
            <!-- Loading -->
            <template v-if="loading">
              <tr v-for="i in 5" :key="i">
                <td v-for="j in 7" :key="j" class="px-4 py-3">
                  <div class="h-4 bg-gray-100 rounded animate-pulse" />
                </td>
              </tr>
            </template>
            <!-- Empty -->
            <tr v-else-if="!invoices.length">
              <td colspan="7" class="px-4 py-12 text-center text-gray-400">No invoices found</td>
            </tr>
            <!-- Rows -->
            <tr v-else v-for="inv in invoices" :key="inv.id" class="hover:bg-gray-50/50 transition-colors">
              <td class="px-4 py-3 text-sm text-gray-700 font-medium">{{ inv.customer_name }}</td>
              <td class="px-4 py-3 text-sm text-gray-700 text-right">{{ formatCurrency(inv.amount) }}</td>
              <td class="px-4 py-3 text-sm text-gray-700 text-right">{{ formatCurrency(inv.total_paid) }}</td>
              <td class="px-4 py-3 text-sm text-gray-700">{{ dayjs(inv.due_date).format('MMM D, YYYY') }}</td>
              <td class="px-4 py-3"><StatusBadge :status="inv.status" /></td>
              <td class="px-4 py-3 text-sm text-gray-500">{{ dayjs(inv.issued_at).format('MMM D, YYYY') }}</td>
              <td class="px-4 py-3 text-right">
                <div class="flex items-center justify-end gap-1">
                  <button
                    @click="handleDownloadPdf(inv)"
                    title="Download PDF"
                    class="p-1.5 rounded-lg text-gray-400 hover:text-primary hover:bg-orange-50 transition-colors"
                  >
                    <svg class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" /></svg>
                  </button>
                  <button
                    @click="handlePrint(inv)"
                    title="Print"
                    class="p-1.5 rounded-lg text-gray-400 hover:text-blue-600 hover:bg-blue-50 transition-colors"
                  >
                    <svg class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M5 4v3H4a2 2 0 00-2 2v3a2 2 0 002 2h1v2a2 2 0 002 2h6a2 2 0 002-2v-2h1a2 2 0 002-2V9a2 2 0 00-2-2h-1V4a2 2 0 00-2-2H7a2 2 0 00-2 2zm8 0H7v3h6V4zm0 8H7v4h6v-4z" clip-rule="evenodd" /></svg>
                  </button>
                  <button
                    v-if="inv.status !== 'void' && inv.status !== 'paid'"
                    @click="openVoidConfirm(inv)"
                    title="Void invoice"
                    class="p-1.5 rounded-lg text-gray-400 hover:text-red-600 hover:bg-red-50 transition-colors"
                  >
                    <svg class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" /></svg>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <Pagination
        :page="page"
        :page-size="pageSize"
        :total="total"
        @update:page="page = $event"
      />
    </div>

    <!-- Generate for Customer Modal -->
    <Modal :open="showGenerateModal" title="Generate Invoice for Customer" @close="showGenerateModal = false; customerSearch = ''; selectedCustomer = null">
      <div class="space-y-4">
        <div class="relative">
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Search Customer</label>
          <input
            v-model="customerSearch"
            @input="onCustomerSearch"
            @focus="showCustomerDropdown = true"
            type="text"
            placeholder="Type customer name..."
            class="w-full px-3 py-2 rounded-lg border border-gray-300 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-colors"
          />
          <!-- Dropdown -->
          <div
            v-if="showCustomerDropdown && (customerResults.length || customerSearchLoading)"
            class="absolute z-10 mt-1 w-full bg-white rounded-lg border border-gray-200 shadow-lg max-h-48 overflow-y-auto"
          >
            <div v-if="customerSearchLoading" class="px-4 py-3 text-sm text-gray-400">Searching...</div>
            <button
              v-else
              v-for="c in customerResults"
              :key="c.id"
              @click="selectCustomer(c)"
              class="w-full text-left px-4 py-2.5 text-sm hover:bg-gray-50 transition-colors"
            >
              <span class="font-medium text-gray-800">{{ c.full_name }}</span>
              <span class="text-gray-400 ml-2">{{ c.pppoe_username }}</span>
            </button>
          </div>
        </div>
        <div v-if="selectedCustomer" class="rounded-lg bg-orange-50 border border-orange-100 px-4 py-3 text-sm text-gray-700">
          Selected: <strong>{{ selectedCustomer.full_name }}</strong>
          <span v-if="selectedCustomer.plan" class="text-gray-500 ml-1">({{ selectedCustomer.plan.name }})</span>
        </div>
      </div>
      <template #footer>
        <button
          @click="showGenerateModal = false; customerSearch = ''; selectedCustomer = null"
          class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
        >
          Cancel
        </button>
        <button
          @click="handleGenerateForCustomer"
          :disabled="!selectedCustomer || generateCustomerLoading"
          class="px-4 py-2 text-sm font-medium text-white bg-primary rounded-lg hover:bg-primary-hover transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ generateCustomerLoading ? 'Generating...' : 'Generate' }}
        </button>
      </template>
    </Modal>

    <!-- Generate All Confirm -->
    <ConfirmDialog
      :open="showGenerateAllConfirm"
      title="Generate All Invoices"
      message="This will generate invoices for all eligible customers. Are you sure you want to proceed?"
      confirm-text="Generate All"
      :loading="generateAllLoading"
      @confirm="handleGenerateAll"
      @cancel="showGenerateAllConfirm = false"
    />

    <!-- Void Confirm -->
    <ConfirmDialog
      :open="showVoidConfirm"
      title="Void Invoice"
      :message="`Are you sure you want to void the invoice for ${voidTarget?.customer_name}? This action cannot be undone.`"
      confirm-text="Void Invoice"
      :danger="true"
      :loading="voidLoading"
      @confirm="handleVoid"
      @cancel="showVoidConfirm = false; voidTarget = null"
    />
  </div>
</template>
